### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by makarasty** [xct007/tiktok-scraper#1]
![изображение](https://user-images.githubusercontent.com/71918286/204556871-c81de5c1-ddf8-41d5-aff3-5731997ee562.png)

**Comment by xct007** [comment]
I'll fix it later 🙂

**Comment by xct007** [comment]
> ![изображение](https://user-images.githubusercontent.com/71918286/204556871-c81de5c1-ddf8-41d5-aff3-5731997ee562.png)

hi, can you show me your code when you use the module?
