### ISSUE TITLE
From where you get this id const "ZGJBtcsDq"

### ISSUE THREAD

**Issue by abdullahafzaldev** [xct007/tiktok-scraper#2]
In the URL 
let url = "https://vt.tiktok.com/ZGJBtcsDq/";
there's one id name as ZGJBtcsDq from wher we can get it

**Comment by xct007** [comment]
I guess there is a share button on tiktok.

**Comment by abdullahafzaldev** [comment]
How share button is gonna help with this user id

**Comment by abdullahafzaldev** [comment]
Okay, Got it 

But is there any way we can scrap the data from @username

**Comment by abdullahafzaldev** [comment]
Can you help me with this, I can pay you for that

**Comment by xct007** [comment]
> Okay, Got it
> 
> But is there any way we can scrap the data from @username

Maybe we can.

**Comment by xct007** [comment]
> Can you help me with this, I can pay you for that

I'll try :)

**Comment by xct007** [comment]
> Okay, Got it
> 
> But is there any way we can scrap the data from @username

Here some results that I can scrape.
![Result](https://telegra.ph/file/9361e7c79f10304f4afa7.jpg)

**Comment by abdullahafzaldev** [comment]
That's amazing,

Great work boy

**Comment by abdullahafzaldev** [comment]
Can we have a meeting call,  To discuss this further

Let me know when you are available
