### ISSUE TITLE
ERROR GET USER DATA

### ISSUE THREAD

**Issue by ezhasyafaat** [xct007/tiktok-scraper#6]
The error indicates that the TikTok scraper is unable to fetch the aweme ID for the given TikTok profile. This could be due to various reasons such as network issues, changes in TikTok's API, or the profile being inaccessible. The specific error suggests that the scraper is encountering undefined data when trying to match the aweme ID pattern, which might imply that the expected response structure has changed or is not being received correctly

**Comment by xct007** [comment]
Thank you for the detailed explanation. To clarify, the script is designed specifically for TikTok content like reels and posts, and unfortunately, it does not support scraping TikTok profile URLs. This might be why you're encountering issues with fetching the aweme ID from a profile. Let me know if you have any further questions!
